language: go

sudo: required

go:
  - 1.7.5
  - 1.8

services:
  - postgresql

env:
  - DEX_POSTGRES_DATABASE=postgres DEX_POSTGRES_USER=postgres DEX_POSTGRES_HOST="localhost" DEX_LDAP_TESTS=1 DEBIAN_FRONTEND=noninteractive


install:
  - wget https://github.com/kubernetes/minikube/releases/download/v0.17.1/minikube_0.17-1.deb
  - sudo dpkg -i minikube_0.17-1.deb
  - go get -u github.com/golang/lint/golint
  - sudo -E apt-get install -y --force-yes slapd time ldap-utils
  - sudo /etc/init.d/slapd stop


script:
  - make testall

notifications:
  email: false
