issuer: http://192.168.56.110:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 0.0.0.0:5556
oauth2:
  skipApprovalScreen: true

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: openldap.cwc.marathon.mesos:389

    # No TLS for this setup.
    insecureNoSSL: true
    
    # This would normally be a read-only user.
    bindDN: cn=admin,dc=k2data,dc=com,dc=cn
    bindPW: k2
    
    userSearch:
      baseDN: ou=ops,dc=k2data,dc=com,dc=cn
      filter: "(objectClass=person)"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn
    
    groupSearch:
      baseDN: cn=groups,dc=k2data,dc=com,dc=cn
      filter: "(objectClass=groupOfNames)"
      
      # A user is a member of a group when their DN matches
      # the value of a "member" attribute on the group entity.
      userAttr: DN
      groupAttr: member
    
      # The group name should be the "cn" value.
      nameAttr: cn

staticClients:
- id: example-app
  redirectURIs:
  - 'http://192.168.56.110:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
