name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make testall-e2e

      - name: Lint
        run: make lint

      # Ensure proto generation doesn't depend on external packages.
      - name: Verify proto
        run: make verify-proto
